# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "2.4.5.dev0+gd8c8d81.d20230903"
__version_tuple__ = version_tuple = (2, 4, 5, "dev0", "gd8c8d81.d20230903")
